# Generated by Django 3.1.2 on 2020-10-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_compelted', models.IntegerField(default=0)),
                ('clients', models.IntegerField(default=0)),
                ('coffe', models.IntegerField(default=0)),
                ('real_professionals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='services/')),
                ('description', models.TextField(max_length=110)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
